# Generated by Django 4.1.3 on 2022-12-02 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('serial_no', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('types', models.CharField(choices=[('PHONE', 'Phone'), ('TABLATE', 'Tablate'), ('LAPTOP', 'Laptop'), ('GEAR', 'Gear')], max_length=255)),
                ('status', models.CharField(choices=[('GOOD', 'Good'), ('REPAIR', 'Repair'), ('MISSING', 'Missing')], max_length=255)),
                ('is_assigned', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='AssetDeligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handover_at', models.DateTimeField()),
                ('handover_type', models.CharField(choices=[('TAKE', 'Take'), ('RETURN', 'Return')], max_length=255)),
                ('reason', models.TextField(max_length=255)),
                ('condition', models.CharField(choices=[('GOOD', 'Good'), ('BROKEN', 'Broken')], max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='assets.asset')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_asset', to='employees.employee')),
            ],
        ),
    ]
