# Generated by Django 4.1.3 on 2022-12-02 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetdeligation',
            name='handover_at',
        ),
        migrations.RemoveField(
            model_name='assetdeligation',
            name='handover_type',
        ),
        migrations.AddField(
            model_name='assetdeligation',
            name='expire_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetdeligation',
            name='given_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetdeligation',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('REFARBISHED', 'Refarbished'), ('OLD', 'Old')], default='NEW', max_length=255),
        ),
        migrations.AlterField(
            model_name='assetdeligation',
            name='condition',
            field=models.CharField(choices=[('GRANT', 'Grant'), ('TEMPORART', 'Temporary'), ('GIFT', 'Gift')], max_length=255),
        ),
    ]
